###
GET http://localhost:8082/api/racks HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8082/api/warehouses HTTP/1.1
Content-Type: application/json
Accept: application/json

###
POST http://localhost:8082/api/racks HTTP/1.1
Content-Type: application/json

{
  "uuid": "{{$guid}}",
  "type": "C",
  "warehouseId": "64061ac04ddbf87b3026cba7"
}

###
POST http://localhost:8082/api/racks HTTP/1.1
Content-Type: application/json

{
  "uuid": "{{$guid}}",
  "type": "B",
  "warehouseId": "64061ac04ddbf87b3026cba7"
}

###
POST http://localhost:8082/api/racks HTTP/1.1
Content-Type: application/json

{
  "uuid": "{{$guid}}",
  "type": "D",
  "warehouseId": "64061ac04ddbf87b3026cba7"
}

###
POST http://localhost:8082/api/warehouses HTTP/1.1
Content-Type: application/json

{
  "uuid": "{{$guid}}",
  "client": "pepe",
  "family": "EST",
  "size": 100
}

###
GET http://localhost:8082/api/warehouses/64061ac04ddbf87b3026cba7/permutate HTTP/1.1
Content-Type: application/json
